{
 "title": "Dashboard - __VM_NAME__",
 "tags": [
  "zabbix",
  "linux"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Status - __VM_NAME__",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "Zabbix agent availability" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Usage - __VM_NAME__",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Memory Usage - __VM_NAME__",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network Traffic - __VM_NAME__",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "Interface ens33: Bits sent" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "Interface ens33: Bits received" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Disk I/O - __VM_NAME__",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "sda: Disk write rate" },
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "group": { "filter": "Linux servers" },
     "host": { "filter": "__VM_NAME__" },
     "application": { "filter": "" },
     "item": { "filter": "sda: Disk read rate" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}